name: abet
description: Aggregation builder example template.
version: 1.0.0

environment:
  sdk: '>=2.10.4 <3.0.0'

dependencies:
  build: ^1.5.1
  glob: ^1.2.0
  path: ^1.7.0
  source_gen: ^0.9.8

dev_dependencies:
  build_runner: ^1.10.6
  pedantic: ^1.9.0
  test: ^1.14.4